// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestApi.Data;

#nullable disable

namespace RestApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230719095809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestApi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("AdminIdIndex");

                    b.ToTable("admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "FUOWnXgFu6p2dPfBLI6Pn8Z/+F5pneWR04mWQ6I+iX8=",
                            Username = "test_admin"
                        });
                });

            modelBuilder.Entity("RestApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("cb41ac92-7eb7-4466-adc8-f664aa523e97"))
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("UserIdIndex");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a0e5748-fde0-4886-91c4-ec36b6eb3a5b"),
                            Age = 37,
                            Name = "Tom"
                        },
                        new
                        {
                            Id = new Guid("6e3b1f1a-c8e8-403a-b368-c7b602d1a603"),
                            Age = 41,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = new Guid("f16011bb-f448-47f3-8c5a-1e6fc0a636fb"),
                            Age = 24,
                            Name = "Sam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
