version: "3.9"

services:
  UrlShortener:
    build:
      dockerfile: Dockerfile
    container_name: UrlShortener
    networks:
      - shared
    ports:
      - "80:80"
 
  pgsql:
    container_name: pgsql
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=test_pass
    healthcheck:
      test: pg_isready -U admin -d test_pass
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - shared
    volumes:
      - /var/www/services/UrlShortener/storages/postgres:/var/lib/postgresql/data/

networks:
  shared:
    driver: bridge

volumes:
  pgsql:
    driver: local